language: elixir
elixir:
- '1.4.5'
script:
- mix test --exclude pending
cache:
  directories:
  - _deps
  - build

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then mix docs; npm install git-update-ghpages; ./node_modules/.bin/git-update-ghpages -e; fi
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: nobody@nobody.org
  - GITHUB_REPO: rstacruz/authsense
  - GIT_SOURCE: doc
